language: java

sudo: required
dist: trusty

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      - alex

before_script:
  - curl -L -o frege.jar https://github.com/Frege/frege/releases/download/3.23.288/frege3.23.422-ga05a487.jar

script:
- alex --version
- make dist
- make test