language: java

dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - sudo apt-get install -yq cabal-install proguard
  - cabal update
  - cabal install alex-3.1.7
  - PATH=$PATH:$HOME/.cabal/bin
  - curl -L -o proguard.tgz https://sourceforge.net/projects/proguard/files/proguard/5.2/proguard5.2.1.tar.gz
  - tar -xvzf proguard.tgz
  - sudo ln -s proguard5.2.1/bin/proguard.sh /usr/bin/proguard
  - curl -L -o frege.jar https://github.com/Frege/frege/releases/download/3.23.288/frege3.23.422-ga05a487.jar

script:
- proguard
- alex --version
- make dist
- make test